<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "x4ebase"
 *
 * Auto generated by Extension Builder 2013-08-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '4eyes Base',
	'description' => 'Basic extbase and fluid functionality, models and viewhelpers',
	'category' => 'misc',
	'author' => 'Christoph Dörfel',
	'author_email' => 'christoph@4eyes.ch',
	'author_company' => '4eyes GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'php' => '5.3.7-0.0.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>