<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "x4ebase"
 *
 * Auto generated by Extension Builder 2013-08-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '4eyes Base',
    'description' => 'Basic extbase and fluid functionality, models and viewhelpers',
    'category' => 'misc',
    'author' => 'Alessandro Bellafronte, Michel Georgy',
    'author_email' => 'alessandro@4eyes.ch, michel@4eyes.ch',
    'author_company' => '4eyes GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '9.0.13',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
            'php' => '7.0.0-7.3.99'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
